version: "3"
services:
  app:
    build: .
    container_name: xpense-app
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app
    depends_on:
      - db  
  db:
    image: couchdb
    container_name: xpense-db
    ports:
      - 5984:5984 
    env_file:
    - .env
    environment:
      COUCHDB_USER: "${COUCHDB_USER}"
      COUCHDB_PASSWORD: "${COUCHDB_PASSWORD}"  

