import { makeStyles } from "@material-ui/core";

const LoginStyle = makeStyles((theme) => ({
  wrapper: {
    background: "#e6f2ff 0% 0% no-repeat padding-box",
    width: "100%",
    height: "100vh",
    display: "grid",
    gridTemplateColumns: "1fr",
    [theme.breakpoints.up("md")]: {
      gridTemplateColumns: "repeat(2, 1fr)",
    },
  },
  imgXpense: {
    position: "relative",
    display: "none",
    [theme.breakpoints.up("md")]: { display: "block" },
  },
  imgX: {
    width: "100%",
    height: 480,
    position: "absolute",
    top: 0,
    bottom: 0,
    left: "-17%",
    right: 0,
    margin: "auto",
  },
  nameXpense: {
    position: "absolute",
    font: "normal normal 600 14px/19px Open Sans",
    color: "#ffffff",
    top: "48.6%",
    bottom: 0,
    left: "42%",
    right: 0,
    margin: "auto",
  },
  loginContent: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#ffffff",
  },
  title: { font: "normal normal normal 27px/41px COCOGOOSE", color: "#07114b" },
  welcome: { font: "normal normal bold 37px/52px Open Sans", color: "#2f45c5" },
  btnGoogle: {
    position: "relative",
    border: "none",
    width: 400,
    height: 40,
    background: "#ffffff 0% 0% no-repeat padding-box",
    boxShadow: "0px 1px 3px #00000026",
    borderRadius: 30,
    color: "#07114B",
    display: "inline-block",
    font: "normal normal 600 15px/20px Open Sans",
  },
  imgGoogle: { position: "absolute", left: theme.spacing(3) },
  inputLogin: {
    background: "#ffffff 0% 0% no-repeat padding-box",
    width: 400,
    height: 40,
    paddingLeft: 30,
    boxShadow: "0px 1px 3px #00000012",
    border: "1px solid #9babc554",
    borderRadius: 30,
    color: "#07114b",
    "&:focus": {
      boxShadow: "none !important",
      border: "1px solid #2f45c5",
      outline: 0,
    },
    "&::placeholder": { color: "#07114b" },
  },
  emailPassword: { position: "relative" },
  iconEemailPassword: {
    position: "absolute",
    left: "90%",
    top: "20%",
    color: "#07114b",
    cursor: "pointer",
  },
  textSm: { fontSize: "14px !important", color: "#07114b" },
  buttonFocus: { boxShadow: "none !important", outline: 0 },
  lineEnd: { borderBottom: "1px solid #f2f2f2" },
  btnSubmit: {
    border: "none",
    marginBottom: theme.spacing(1.5),
    width: 400,
    height: 40,
    background: "#2f45c5 0% 0% no-repeat padding-box",
    borderRadius: 30,
    color: "#ffffff",
    font: "normal normal 600 16px/22px Open Sans",
  },
  alertError: {
    textAlign: "left",
    font: "normal normal bold 12px/22px Open Sans",
    color: "#fb2b76",
  },
  welcomeRegister: {
    font: "normal normal bold 37px/52px Open Sans",
    color: "#2f45c5",
  },
  select: { fontSize: "14px/19px" },
  selectRegister: { width: 400, height: 40, paddingLeft: 25 },
  forgotPassword: {
    font: "normal normal bold 25px/35px Open Sans",
    color: "#2F45C5",
  },
  txt: {
    textAlign: "center",
    font: "normal normal 300 15px/21px Open Sans",
    color: "#07114B",
    paddingLeft: theme.spacing(10),
    paddingRight: theme.spacing(10),
  },
  btnCancel: {
    width: 110,
    height: 30,
    background: "#ffffff 0% 0% no-repeat padding-box",
    border: "1px solid #fb2b76",
    borderRadius: 30,
    font: "normal normal 600 13px/17px Open Sans",
    color: "#fb2b76",
  },
  emailSend: {
    font: "normal normal bold 25px/35px Open Sans",
    color: "#2F45C5",
  },
  txtEs: {
    textAlign: "center",
    font: "normal normal 300 14px/17px Open Sans",
    color: "#07114B",
    paddingLeft: theme.spacing(18),
    paddingRight: theme.spacing(18),
  },
  plan: {
    background: "#f9fafe 0% 0% no-repeat padding-box",
    width: "100%",
    height: "100vh",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
  },
  checkImg: { width: 100, height: 95 },
  box: {
    width: "50%",
    height: 380,
    background: "#ffffff 0% 0% no-repeat padding-box",
    boxShadow: "0px 1px 8px #00000008",
    borderRadius: 17,
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
  },
  step: { font: "normal normal 800 28px/38px Open Sans", color: " #fb2b76" },
  txtConfirm: {
    textAlign: "center",
    font: "normal normal 300 16px/22px Open Sans",
    color: "#07114B",
    paddingLeft: theme.spacing(5),
    paddingRight: theme.spacing(5),
  },
  emailInvitation: {
    textAlign: "center",
    font: "normal normal 600 16px/22px Open Sans",
    color: "#2F45C5",
  },
}));

export default LoginStyle;
