version: '3.7'

services:

  api:
    image: ${API_IMG}
    container_name: '${COMPOSE_PROJECT_NAME}-API'
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - ./envfiles/api.env:/app/.env:ro

  app:
    image: ${APP_IMG}
    container_name: '${COMPOSE_PROJECT_NAME}-APP'
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - ./envfiles/app.env:/app/.env:ro
    depends_on: 
      - api