version: '3.7'

services:

  api:
    image: ${API_IMG}
    container_name: '${COMPOSE_PROJECT_NAME}-API'
    ports:
      - ${API_PORT}:${API_PORT}
    environment:
      PORT: '${API_PORT}'
      COUCHDB_USER: ${COUCHDB_USER}
      COUCHDB_PASSWORD: ${COUCHDB_PASSWORD}
      COUCHDB_DBNAME: ${COUCHDB_DBNAME}
      COUCHDB_URL: ${COUCHDB_URL}
      AUTH0_AUDIENCE: ${AUTH0_AUDIENCE}
      AUTH0_ISSUER: ${AUTH0_ISSUER}
      AUTH0_RULE_PREFIX_KEY: ${AUTH0_RULE_PREFIX_KEY}
      AUTH_MANAGEMENT_CLIENT_ID: ${AUTH_MANAGEMENT_CLIENT_ID}
      AUTH_MANAGEMENT_CLIENT_SECRET: ${AUTH_MANAGEMENT_CLIENT_SECRET}
      AUTH_MANAGEMENT_CLIENT_DOMAIN: ${AUTH_MANAGEMENT_CLIENT_DOMAIN}