version: '3'
services:
  xpense-api:
    build: .
    container_name: xpense-api
    restart: unless-stopped
    ports:
      - "7000:7000"
    volumes:
      - ".:/app" 
    env_file:
      - .env  
  